static const char black[] = "#1E1E2E";
static const char gray2[] = "#282737"; // unfocused window border
static const char gray3[] = "#585767";
static const char gray4[] = "#282737";
static const char blue[] = "#89B4FA"; // focused window border
static const char green[] = "#A6E3A1";
static const char red[] = "#F38BA8";
static const char peach[] = "#FAB387";
static const char yellow[] = "#F9E2AF";
static const char pink[] = "#F5C2E7";
static const char col_borderbar[] = "#1E1D2D"; // inner border
static const char text[] = "#CDD6F4";
static const char rosewater[] = "#F5E0DC";
static const char flamingo[] = "#F2CDCD";
static const char mauve[] = "#CBA6F7";
static const char maroon[] = "#eBA0AC";
static const char teal[] = "#94E2D5";
static const char sky[] = "#89DCEB";
static const char sapphire[] = "#74C7EC";
static const char lavender[] = "#B4BEFE";
